local wk = require("which-key")
wk.setup({})
wk.add({
  { "<leader>a", group = "files" },
  { "<leader>ac", ':let @+ = expand("%")<CR>', desc = "copy path" },
  { "<leader>ad", ":call delete(expand('%')) | bdelete!", desc = "delete" },
  { "<leader>ae", ":NvimTreeToggle<CR>", desc = "tree toggle" },
  { "<leader>af", ":NvimTreeFocus<CR>", desc = "tree focus" },
  { "<leader>ax", ":NvimTreeFindFile<CR>", desc = "tree find file" },
  { "<leader>a?", "<cmd>echo 'Press g? in NvimTree for help'<CR>", desc = "tree help (press g?)" },
  { "<leader>c", group = "comment" },
  { "<leader>f", group = "find" },
  { "<leader>fa", "<Cmd>lua require('telescope.builtin').oldfiles()<CR>", desc = "recent files" },
  { "<leader>fb", "<Cmd>Telescope buffers<CR>", desc = "buffers" },
  { "<leader>fc", group = "commands" },
  { "<leader>fcc", "<Cmd>Telescope commands<CR>", desc = "commands" },
  { "<leader>fch", "<Cmd>Telescope command_history<CR>", desc = "history" },
  { "<leader>fd", "<Cmd>Telescope file_browser path=%:p:h select_buffer=true<CR>", desc = "directory browser" },
  { "<leader>ff", "<Cmd>lua require('telescope.builtin').find_files({ hidden = true })<CR>", desc = "files" },
  { "<leader>fg", "<Cmd>Telescope live_grep<CR>", desc = "file contents" },
  { "<leader>fl", ":Telescope live_grep find_command=rg,--ignore,--hidden,--fixed-strings,--files<CR>", desc = "file contents (literal)" },
  { "<leader>fh", "<Cmd>Telescope help_tags<CR>", desc = "help tags" },
  { "<leader>fi", "<Cmd>Telescope media_files<CR>", desc = "images/media" },
  { "<leader>fq", "<Cmd>Telescope quickfix<CR>", desc = "quickfix" },
  { "<leader>fs", "<Cmd>Telescope search_history<CR>", desc = "search history" },
  { "<leader>ft", "<Cmd>lua require('telescope.builtin').resume()<CR>", desc = "resume search" },
  { "<leader>g", group = "git" },
  { "<leader>gs", "<Cmd>Telescope git_status<CR>", desc = "status" },
  { "<leader>s", group = "whitespace" },
  { "<leader>st", "<Cmd>call WhitespaceToggle()<CR>", desc = "toggle" },
  { "<leader>t", group = "tab" },
  { "<leader>td", "<Cmd>lua DuplicateWindow()<CR>", desc = "duplicate" },
  { "<leader>w", ":w!<CR>", desc = "save file" },
  { "<leader>x", group = "vim" },
  { "<leader>xc", ":checkhealth<CR>", desc = "check health" },
  { "<leader>xr", ":source $MYVIMRC<CR>", desc = "reload config" },
})
